In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data\\cleaned_facebook_ads.csv')

In [3]:
df.head()

,ad_id,xyz_campaign_id,fb_campaign_id,age,gender,interest,impressions,clicks,spent,Total_Conversion,Approved_Conversion
0,708746,916,103916,30-34,M,15,7350,1,1.43,2,1
1,708749,916,103917,30-34,M,16,17861,2,1.82,2,0
2,708771,916,103920,30-34,M,20,693,0,0.00,1,0
3,708815,916,103928,30-34,M,28,4259,1,1.25,1,0
4,708818,916,103928,30-34,M,28,4133,1,1.29,1,1

# Click Through Rate (CTR)
CTR = (Clicks / Impressions) * 100

In [4]:
df['CTR'] = (df['clicks'] / df['impressions']) * 100

# Click Per Click (CPC)
CPC = Spent / Clicks

In [5]:
df['CPC'] = df['spent'] / df['clicks']

# Cost Per Mille (CPM)
Cost per 1000 impression

CPM = (Spent / Impression) * 1000

In [6]:
df['CPM'] = (df['spent'] / df['impressions']) * 1000

# Conversion Rate
Conversion Rate = (Total_Conversion / clicks) * 100

In [7]:
df['Conversion_rate'] = (
    df['Total_Conversion'] / df['clicks']
) * 100

# Approved conversion rate
Approved conversion rate = Approved_conversion / Total_conversion * 100

In [8]:
df['Approved_Conversion_Rate'] = (
    df['Approved_Conversion'] /
    df['Total_Conversion']
) * 100

# Cost per conversion
CPA = Spent / Total_Conversion

In [9]:
df['CPA'] = df['spent'] / df['Total_Conversion']

# Cost Per Approved Conversion
Spent / Approved_Conversion

In [10]:
df['Cost_Per_Approved'] = (
    df['spent'] /
    df['Approved_Conversion']
)

# Conversion per 1000 Impressions

In [11]:
df['Conversions_per_1000'] = (
    df['Total_Conversion'] /
    df['impressions']
) * 1000

In [12]:
df.head()

,ad_id,xyz_campaign_id,fb_campaign_id,age,gender,interest,impressions,clicks,spent,Total_Conversion,Approved_Conversion,CTR,CPC,CPM,Conversion_rate,Approved_Conversion_Rate,CPA,Cost_Per_Approved,Conversions_per_1000
0,708746,916,103916,30-34,M,15,7350,1,1.43,2,1,0.013605,1.43,0.194558,200.0,50.0,0.715,1.43,0.272109
1,708749,916,103917,30-34,M,16,17861,2,1.82,2,0,0.011198,0.91,0.101898,100.0,0.0,0.910,inf,0.111976
2,708771,916,103920,30-34,M,20,693,0,0.00,1,0,0.000000,NaN,0.000000,inf,0.0,0.000,NaN,1.443001
3,708815,916,103928,30-34,M,28,4259,1,1.25,1,0,0.023480,1.25,0.293496,100.0,0.0,1.250,inf,0.234797
4,708818,916,103928,30-34,M,28,4133,1,1.29,1,1,0.024195,1.29,0.312122,100.0,100.0,1.290,1.29,0.241955

# Handle Infinite Values

In [13]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)

In [14]:
df.fillna(0, inplace=True)

In [15]:
df.head()

,ad_id,xyz_campaign_id,fb_campaign_id,age,gender,interest,impressions,clicks,spent,Total_Conversion,Approved_Conversion,CTR,CPC,CPM,Conversion_rate,Approved_Conversion_Rate,CPA,Cost_Per_Approved,Conversions_per_1000
0,708746,916,103916,30-34,M,15,7350,1,1.43,2,1,0.013605,1.43,0.194558,200.0,50.0,0.715,1.43,0.272109
1,708749,916,103917,30-34,M,16,17861,2,1.82,2,0,0.011198,0.91,0.101898,100.0,0.0,0.910,0.00,0.111976
2,708771,916,103920,30-34,M,20,693,0,0.00,1,0,0.000000,0.00,0.000000,0.0,0.0,0.000,0.00,1.443001
3,708815,916,103928,30-34,M,28,4259,1,1.25,1,0,0.023480,1.25,0.293496,100.0,0.0,1.250,0.00,0.234797
4,708818,916,103928,30-34,M,28,4133,1,1.29,1,1,0.024195,1.29,0.312122,100.0,100.0,1.290,1.29,0.241955

In [16]:
df.describe()

,ad_id,xyz_campaign_id,fb_campaign_id,interest,impressions,clicks,spent,Total_Conversion,Approved_Conversion,CTR,CPC,CPM,Conversion_rate,Approved_Conversion_Rate,CPA,Cost_Per_Approved,Conversions_per_1000
count,1.143000e+03,1143.000000,1143.000000,1143.000000,1.143000e+03,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,9.872611e+05,1067.382327,133783.989501,32.766404,1.867321e+05,33.390201,51.360656,2.855643,0.944007,0.016420,1.227812,0.239387,24.169930,33.670667,16.016721,20.719900,0.252510
std,1.939928e+05,121.629393,20500.308622,26.952131,3.127622e+05,56.892438,86.908418,4.483593,1.737708,0.011506,0.614889,0.160908,36.838128,40.114345,24.297504,43.761027,0.712050
min,7.087460e+05,916.000000,103916.000000,2.000000,8.700000e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7.776325e+05,936.000000,115716.000000,16.000000,6.503500e+03,1.000000,1.480000,1.000000,0.000000,0.010022,1.234500,0.148742,2.857143,0.000000,1.380000,0.000000,0.012122
50%,1.121185e+06,1178.000000,144549.000000,25.000000,5.150900e+04,8.000000,12.370000,1.000000,1.000000,0.015981,1.450000,0.248816,9.090909,15.384615,8.190000,0.000000,0.030699
75%,1.121804e+06,1178.000000,144657.500000,31.000000,2.217690e+05,37.500000,60.025000,3.000000,1.000000,0.023364,1.600000,0.332700,25.000000,54.545455,21.229286,24.075000,0.169406
max,1.314415e+06,1178.000000,179982.000000,114.000000,3.052003e+06,421.000000,639.949998,60.000000,21.000000,0.105932,2.212000,1.504237,400.000000,100.000000,332.989999,352.449999,11.494253

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ad_id                     1143 non-null   int64
 1   xyz_campaign_id           1143 non-null   int64
 2   fb_campaign_id            1143 non-null   int64
 3   age                       1143 non-null   object
 4   gender                    1143 non-null   object
 5   interest                  1143 non-null   int64
 6   impressions               1143 non-null   int64
 7   clicks                    1143 non-null   int64
 8   spent                     1143 non-null   float64
 9   Total_Conversion          1143 non-null   int64
 10  Approved_Conversion       1143 non-null   int64
 11  CTR                       1143 non-null   float64
 12  CPC                       1143 non-null   float64
 13  CPM                       1143 non-null   float64
 14  Conversion_rate           1143 non-null   float64
 15  Approved_Conversion_Rate  1143 non-null   float64
 16  CPA                       1143 non-null   float64
 17  Cost_Per_Approved         1143 non-null   float64
 18  Conversions_per_1000      1143 non-null   float64
dtypes: float64(9), int64(8), object(2)
memory usage: 169.8+ KB

# KPI Analysis
Campaign wise KPIs

In [18]:
Total_spend = (
    df.groupby('xyz_campaign_id')['spent'].sum()
)

Total_spend

xyz_campaign_id
916       149.710001
936      2893.369999
1178    55662.149959
Name: spent, dtype: float64

In [19]:
Total_clicks = (
    df.groupby('xyz_campaign_id')['clicks'].sum()
)

Total_clicks

xyz_campaign_id
916       113
936      1984
1178    36068
Name: clicks, dtype: int64

In [20]:
Average_CTR = (
    df.groupby('xyz_campaign_id')['CTR'].mean()
)

Average_CTR

xyz_campaign_id
916     0.018015
936     0.016502
1178    0.016221
Name: CTR, dtype: float64

In [21]:
Average_CPC = (
    df.groupby('xyz_campaign_id')['CPC'].mean()
)

Average_CPC

xyz_campaign_id
916     0.862264
936     0.846742
1178    1.542302
Name: CPC, dtype: float64

In [22]:
Average_CPA = (
    df.groupby('xyz_campaign_id')['CPA'].mean()
)

Average_CPA

xyz_campaign_id
916      2.688981
936      4.897979
1178    25.422791
Name: CPA, dtype: float64

In [23]:
Average_Conversion_rate = (
    df.groupby('xyz_campaign_id')['Conversion_rate'].mean()
)

Average_Conversion_rate

xyz_campaign_id
916     43.955026
936     34.298695
1178    14.940902
Name: Conversion_rate, dtype: float64

In [24]:
df.columns

Index(['ad_id', 'xyz_campaign_id', 'fb_campaign_id', 'age', 'gender',
       'interest', 'impressions', 'clicks', 'spent', 'Total_Conversion',
       'Approved_Conversion', 'CTR', 'CPC', 'CPM', 'Conversion_rate',
       'Approved_Conversion_Rate', 'CPA', 'Cost_Per_Approved',
       'Conversions_per_1000'],
      dtype='object')

# Audience KPI analysis

Age Wise KPIs

In [32]:
Avg_age_ctr = (
    df.groupby('age')['CTR'].mean()
)
Avg_age_ctr

age
30-34    0.011624
35-39    0.016256
40-44    0.020044
45-49    0.021526
Name: CTR, dtype: float64

In [26]:
Avg_age_cpc = (
    df.groupby('age')['CPC'].mean()
)
Avg_age_cpc

age
30-34    1.085405
35-39    1.291788
40-44    1.313651
45-49    1.331184
Name: CPC, dtype: float64

In [27]:
Avg_age_cpa = (
    df.groupby('age')['CPA'].mean()
)
Avg_age_cpa

age
30-34     7.546777
35-39    13.879424
40-44    20.234986
45-49    28.574289
Name: CPA, dtype: float64

# Gender wise KPIs

In [31]:
Avg_gender_ctr = (
    df.groupby('gender')['CTR'].mean()
)
Avg_gender_ctr

gender
F    0.019390
M    0.013655
Name: CTR, dtype: float64

In [33]:
Avg_gender_cpc = (
    df.groupby('gender')['CPC'].mean()
)
Avg_gender_cpc

gender
F    1.200775
M    1.252977
Name: CPC, dtype: float64

In [34]:
Avg_gender_approv = (
    df.groupby('gender')['Approved_Conversion'].mean()
)
Avg_gender_approv

gender
F    0.898367
M    0.986486
Name: Approved_Conversion, dtype: float64

# Interest wise KPIs

In [35]:
Avg_interest_ctr = (
    df.groupby('interest')['CTR'].mean()
)
Avg_interest_ctr

interest
2      0.017237
7      0.013678
10     0.017452
15     0.013141
16     0.014342
18     0.014836
19     0.017909
20     0.020062
21     0.014207
22     0.020489
23     0.015189
24     0.024704
25     0.021487
26     0.017441
27     0.020558
28     0.019606
29     0.015233
30     0.017116
31     0.013938
32     0.013647
36     0.012480
63     0.017048
64     0.015523
65     0.018262
66     0.014143
100    0.014344
101    0.014286
102    0.011528
103    0.014584
104    0.016032
105    0.014737
106    0.019130
107    0.012644
108    0.012429
109    0.017897
110    0.013720
111    0.015379
112    0.010736
113    0.009783
114    0.014483
Name: CTR, dtype: float64

In [36]:
Avg_interest_cpc = (
    df.groupby('interest')['CPC'].mean()
)
Avg_interest_cpc

interest
2      1.132773
7      1.047438
10     1.207063
15     1.145854
16     1.205682
18     1.194558
19     1.378610
20     1.194976
21     1.122742
22     1.331896
23     1.227550
24     1.410129
25     1.311862
26     1.081928
27     1.376702
28     1.234521
29     1.148674
30     1.165443
31     1.042303
32     1.199874
36     1.132322
63     1.252262
64     1.144231
65     1.145590
66     1.473671
100    1.455254
101    1.464570
102    1.412382
103    1.460618
104    1.472001
105    1.449091
106    1.451577
107    1.437342
108    1.464365
109    1.443248
110    1.426412
111    1.428876
112    1.475474
113    1.482452
114    1.502516
Name: CPC, dtype: float64

In [37]:
Avg_interest_cpa = (
    df.groupby('interest')['CPA'].mean()
)
Avg_interest_cpa

interest
2      12.190827
7       9.383506
10     14.533306
15     12.841619
16     16.732909
18     25.703487
19     16.545728
20     11.257136
21     10.777142
22     21.212449
23     22.276609
24     18.776861
25     23.791033
26     18.414347
27     17.424833
28     16.448203
29     13.083114
30     16.175783
31      9.756000
32     17.966040
36      7.185079
63     17.007752
64     15.794126
65     15.647000
66     15.058636
100    10.979495
101    10.160944
102    20.472143
103    19.240595
104    10.709143
105    19.110000
106    27.888308
107    16.719310
108    13.183833
109    23.668791
110    19.858518
111    30.633623
112     9.292500
113    10.626681
114    20.678400
Name: CPA, dtype: float64

# Best and worst Performance
1. According to CTR
2. According to CPC

In [38]:
df.nlargest(10,'CTR')

,ad_id,xyz_campaign_id,fb_campaign_id,age,gender,interest,impressions,clicks,spent,Total_Conversion,Approved_Conversion,CTR,CPC,CPM,Conversion_rate,Approved_Conversion_Rate,CPA,Cost_Per_Approved,Conversions_per_1000
150,738637,936,109857,45-49,F,24,944,1,1.42,1,0,0.105932,1.420,1.504237,100.000000,0.0,1.420,0.00,1.059322
440,950224,936,123464,40-44,M,20,2367,2,2.84,1,1,0.084495,1.420,1.199831,50.000000,100.0,2.840,2.84,0.422476
505,951779,936,123723,45-49,F,27,3277,2,2.68,1,0,0.061031,1.340,0.817821,50.000000,0.0,2.680,0.00,0.305157
476,951202,936,123627,45-49,F,26,5307,3,4.29,2,1,0.056529,1.430,0.808366,66.666667,50.0,2.145,4.29,0.376861
448,950537,936,123516,40-44,M,36,1884,1,1.41,1,0,0.053079,1.410,0.748408,100.000000,0.0,1.410,0.00,0.530786
255,776780,936,115561,40-44,M,2,3812,2,3.05,1,0,0.052466,1.525,0.800105,50.000000,0.0,3.050,0.00,0.262329
445,950495,936,123509,45-49,M,21,1909,1,0.98,1,0,0.052383,0.980,0.513358,100.000000,0.0,0.980,0.00,0.523834
202,748314,936,111020,45-49,F,31,7821,4,6.34,1,1,0.051144,1.585,0.810638,25.000000,100.0,6.340,6.34,0.127861
165,747489,936,110882,40-44,M,2,4016,2,1.48,1,1,0.049801,0.740,0.368526,50.000000,100.0,1.480,1.48,0.249004
509,951837,936,123733,45-49,F,20,2077,1,1.51,1,1,0.048146,1.510,0.727010,100.000000,100.0,1.510,1.51,0.481464

In [39]:
df.nlargest(10, "CPC")

,ad_id,xyz_campaign_id,fb_campaign_id,age,gender,interest,impressions,clicks,spent,Total_Conversion,Approved_Conversion,CTR,CPC,CPM,Conversion_rate,Approved_Conversion_Rate,CPA,Cost_Per_Approved,Conversions_per_1000
586,1121223,1178,144558,30-34,M,31,64020,5,11.060000,1,0,0.007810,2.212000,0.172759,20.000000,0.0,11.060000,0.000,0.015620
548,1121129,1178,144537,30-34,M,21,20618,1,2.100000,2,1,0.004850,2.100000,0.101853,200.000000,50.0,1.050000,2.100,0.097003
686,1121413,1178,144592,35-39,M,64,65060,7,14.520000,1,1,0.010759,2.074286,0.223179,14.285714,100.0,14.520000,14.520,0.015370
588,1121229,1178,144561,30-34,M,32,404866,43,87.420001,4,0,0.010621,2.033023,0.215923,9.302326,0.0,21.855000,0.000,0.009880
549,1121131,1178,144537,30-34,M,21,83591,7,14.140000,2,2,0.008374,2.020000,0.169157,28.571429,100.0,7.070000,7.070,0.023926
200,748295,936,111016,45-49,F,27,9240,3,6.040000,1,0,0.032468,2.013333,0.653680,33.333333,0.0,6.040000,0.000,0.108225
199,748294,936,111016,45-49,F,27,82827,24,47.930000,3,0,0.028976,1.997083,0.578676,12.500000,0.0,15.976667,0.000,0.036220
600,1121254,1178,144565,30-34,M,63,124005,11,21.850000,4,1,0.008871,1.986364,0.176203,36.363636,25.0,5.462500,21.850,0.032257
550,1121132,1178,144537,30-34,M,21,114923,12,23.730000,4,2,0.010442,1.977500,0.206486,33.333333,50.0,5.932500,11.865,0.034806
546,1121127,1178,144537,30-34,M,21,40873,4,7.900000,2,1,0.009786,1.975000,0.193282,50.000000,50.0,3.950000,7.900,0.048932

In [40]:
df.to_csv(
    "data\\facebook_ads_feature_engineered.csv",
    index=False
)